openapi: 3.1.0
x-stoplight:
  id: xjgnbymf28s2v
info:
  title: OpenBank
  version: '1.0'
  summary: API לעבודה עם בנקים
  description: תיאור מורחב
servers:
  - url: 'http://localhost:3000'
paths:
  /banks:
    get:
      summary: GetBanks
      tags: []
      responses:
        '200':
          description: 'response example  '
        '201':
          description: Created
      operationId: get-banks
      parameters:
        - schema:
            type: string
          in: header
        - $ref: '#/components/parameters/bankId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  $ref: ../models/Client.yaml
    post:
      summary: ''
      operationId: post-banks
      responses:
        '200':
          description: OK
  /banks/delete: {}
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    '':
      $ref: ../models/Client.yaml
      x-stoplight:
        id: z5w2wavgp826w
  securitySchemes: {}
  parameters:
    bankId:
      name: bankId
      in: query
      required: false
      schema:
        type: integer
      description: מזהה בנק
